org: thisisshit
app: cool-app
service: cool-service

provider:
  name: aws
  region: eu-west-2
  stage: dev
  memorySize: 256
  runtime: nodejs14.x

functions:
  graphql:
    handler: dist/index.handler
    events:
    - http:
        path: /
        method: post
        cors: true